export const genres = [
	{ label: "Action", name: "action" },
	{ label: "Adventure", name: "adventure" },
	{ label: "Comedy", name: "comedy" },
	{ label: "Crime", name: "crime" },
	{ label: "Demons", name: "demons" },
	{ label: "Drama", name: "drama" },
	{ label: "Family", name: "family" },
	{ label: "Fantasy", name: "fantasy" },
	{ label: "Game", name: "game" },
	{ label: "Gourmet", name: "gourmet" },
	{ label: "Harem", name: "harem" },
	{ label: "Historical", name: "historical" },
	{ label: "Horror", name: "horror" },
	{ label: "Magic", name: "magic" },
	{ label: "Martial Arts", name: "martial-arts" },
	{ label: "Mecha", name: "mecha" },
	{ label: "Military", name: "military" },
	{ label: "Mystery", name: "mystery" },
	{ label: "Psychological", name: "psychological" },
	{ label: "Romance", name: "romance" },
	{ label: "Samurai", name: "samurai" },
	{ label: "School", name: "school" },
	{ label: "Sci-Fi", name: "sci-fi" },
	{ label: "Space", name: "space" },
	{ label: "Sports", name: "sports" },
	{ label: "Super Power", name: "super-power" },
	{ label: "Supernatural", name: "supernatural" },
	{ label: "Suspense", name: "suspense" },
	{ label: "Thriller", name: "thriller" },
	{ label: "Vampire", name: "vampire" },
];
